"""product brand column

Revision ID: 28a8dccff2b0
Revises: f3ba47e2d196
Create Date: 2021-03-25 09:04:47.096011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a8dccff2b0'
down_revision = 'f3ba47e2d196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=False, default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
