version: "3.6"
services:
  store-api:
    build: ./src/store-api
    networks:
      - store-network
    ports:
    - 5000:5000
    environment:
      APP_ENV: "docker"

  store-front:
    build: ./src/store-front
    ports:
      - 8000:8000
    environment:
      APP_ENV: "docker"
    networks:
      - store-network

  local-pg:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: app_pass
      POSTGRES_USER: app_user
      POSTGRES_DB: mystore
    networks:
      - store-network

networks:
  store-network: